// nolint
// Copyright 20xx The Alipay Authors.
//
// @authors[0]: bingwu.ybw(bingwu.ybw@antfin.com|detailyang@gmail.com)
// @authors[1]: robotx(robotx@antfin.com)
//
// *Legal Disclaimer*
// Within this source code, the comments in Chinese shall be the original, governing version. Any comment in other languages are for reference only. In the event of any conflict between the Chinese language version comments and other language version comments, the Chinese language version shall prevail.
// *法律免责声明*
// 关于代码注释部分，中文注释为官方版本，其它语言注释仅做参考。中文注释可能与其它语言注释存在不一致，当中文注释与其它语言注释存在不一致时，请以中文注释为准。
//
//

// Code generated by "stringer -type=ServerEvent"; DO NOT EDIT.

package sofabolt

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ServerTemporaryAcceptEvent-0]
	_ = x[ServerWorkerPoolOverflowEvent-1]
	_ = x[ServerConnErrorEvent-2]
	_ = x[ServerConnHijackedEvent-3]
}

const _ServerEvent_name = "ServerTemporaryAcceptEventServerWorkerPoolOverflowEventServerConnErrorEventServerConnHijackedEvent"

var _ServerEvent_index = [...]uint8{0, 26, 55, 75, 98}

func (i ServerEvent) String() string {
	if i >= ServerEvent(len(_ServerEvent_index)-1) {
		return "ServerEvent(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ServerEvent_name[_ServerEvent_index[i]:_ServerEvent_index[i+1]]
}
